# Covid-19 Dataset - Data Cleaning and Processing

### Libraries

In [10]:
#libraries
import pandas as pd
import datetime
import pandas_profiling

In [2]:
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [3]:
# Library used for country name evaluation
import country_converter as coco

In [4]:
from opencage.geocoder import OpenCageGeocode
from pprint import pprint

## Data preparation

#### Data loading

In [7]:
# Dataset load
covid_df = pd.read_csv("covid_19_data.csv")

In [8]:
covid_df.head()

,SNo,ObservationDate,Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered
0,1,01/22/2020,Anhui,Mainland China,1/22/2020 17:00,1.0,0.0,0.0
1,2,01/22/2020,Beijing,Mainland China,1/22/2020 17:00,14.0,0.0,0.0
2,3,01/22/2020,Chongqing,Mainland China,1/22/2020 17:00,6.0,0.0,0.0
3,4,01/22/2020,Fujian,Mainland China,1/22/2020 17:00,1.0,0.0,0.0
4,5,01/22/2020,Gansu,Mainland China,1/22/2020 17:00,0.0,0.0,0.0

#### Data exploration

In [7]:
# Generates profile reports from a pandas DataFrame in an interactive HTML report
pandas_profiling.ProfileReport(covid_df)

/usr/local/anaconda3/lib/python3.7/site-packages/pandas_profiling/describe.py:392: FutureWarning: The join_axes-keyword is deprecated. Use .reindex or .reindex_like on the result to achieve the same functionality.
  variable_stats = pd.concat(ldesc, join_axes=pd.Index([names]), axis=1)

In [8]:
covid_df.info(verbose=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7926 entries, 0 to 7925
Data columns (total 8 columns):
SNo                7926 non-null int64
ObservationDate    7926 non-null object
Province/State     4493 non-null object
Country/Region     7926 non-null object
Last Update        7926 non-null object
Confirmed          7926 non-null float64
Deaths             7926 non-null float64
Recovered          7926 non-null float64
dtypes: float64(3), int64(1), object(4)
memory usage: 495.5+ KB

In [9]:
covid_df.describe()

              SNo     Confirmed       Deaths     Recovered
count  7926.00000   7926.000000  7926.000000   7926.000000
mean   3963.50000    655.640172    22.993187    237.621625
std    2288.18345   4978.076030   229.440512   2704.176057
min       1.00000      0.000000     0.000000      0.000000
25%    1982.25000      2.000000     0.000000      0.000000
50%    3963.50000     16.000000     0.000000      0.000000
75%    5944.75000    130.000000     1.000000     10.000000
max    7926.00000  67800.000000  5476.000000  59433.000000

In [10]:
print(covid_df.shape)

(7926, 8)

In [11]:
covid_df.columns

Index(['SNo', 'ObservationDate', 'Province/State', 'Country/Region',
       'Last Update', 'Confirmed', 'Deaths', 'Recovered'],
      dtype='object')

#### Check for duplicates and missing values

In [12]:
#looking for duplicates
covid_df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
7921    False
7922    False
7923    False
7924    False
7925    False
Length: 7926, dtype: bool

<b><i>No duplicate Values</i></b>

In [13]:
covid_df[covid_df.duplicated()]
covid_df.shape

(7926, 8)

In [14]:
#missing values
covid_df.isna().head(10)

,SNo,ObservationDate,Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered
0,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False

In [15]:
covid_df.isna().sum()

SNo                   0
ObservationDate       0
Province/State     3433
Country/Region        0
Last Update           0
Confirmed             0
Deaths                0
Recovered             0
dtype: int64

<b><i>Missing values in Province/State</i></b>

In [16]:
covid_df["Province/State"].isna()

0       False
1       False
2       False
3       False
4       False
        ...
7921     True
7922     True
7923     True
7924     True
7925     True
Name: Province/State, Length: 7926, dtype: bool

In [17]:
values = {'Province/State': "Unknown"} 
covid_df = covid_df.fillna(value=values)

In [18]:
covid_df.isna(). sum()

SNo                   0
ObservationDate       0
Province/State     3433
Country/Region        0
Last Update           0
Confirmed             0
Deaths                0
Recovered             0
dtype: int64

In [19]:
covid_df.head()

,SNo,ObservationDate,Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered
0,1,01/22/2020,Anhui,Mainland China,1/22/2020 17:00,1.0,0.0,0.0
1,2,01/22/2020,Beijing,Mainland China,1/22/2020 17:00,14.0,0.0,0.0
2,3,01/22/2020,Chongqing,Mainland China,1/22/2020 17:00,6.0,0.0,0.0
3,4,01/22/2020,Fujian,Mainland China,1/22/2020 17:00,1.0,0.0,0.0
4,5,01/22/2020,Gansu,Mainland China,1/22/2020 17:00,0.0,0.0,0.0

### Data Transformation

In [14]:
# convert observation date into a date
covid_df["ObservationDate"]=pd.to_datetime(covid_df["ObservationDate"])

<i>Handling incorrect data</i>

In [ ]:
covid_df['Country/Region'].replace(
    to_replace=["('St. Martin',)"],
    value='St. Martin',
    inplace=True
)
covid_df1 = covid_df['Country/Region'].str.contains('St. Martin') 
covid_df1

In [ ]:
covid_df["Country/Region"].explode().value_counts()

In [ ]:
# Channel Islands +  UK + North Ireland to United Kingdom
covid_df["Country/Region"] = covid_df["Country/Region"].replace({"UK": "United Kingdom",
                                                   "Channel Islands": "United Kingdom",
                                                    "North Ireland": "United Kingdom"}
                                                   )

In [ ]:
# Republic of Ireland  to Ireland
covid_df["Country/Region"] = covid_df["Country/Region"].replace({"Republic of Ireland": "Ireland"}
                                                   )

In [ ]:
#others + delete

covid_new_df = covid_df[covid_df["Country/Region"] != 'Others']

In [ ]:
print(covid_new_df.shape)
print(covid_df.shape)
covid_df.head()

### Include continents

In [ ]:
covid_new_df["Country/Region"].value_counts()

In [ ]:
covid_df["Country/Region"].value_counts()

In [ ]:
covid_new_df =covid_new_df.groupby(["ObservationDate", "Country/Region"], as_index=False)[
      'Confirmed', "Deaths", "Recovered"].sum()
covid_new_df.set_index('ObservationDate', inplace=True)
covid_new_df.head()

In [ ]:
countr= covid_new_df['Country/Region'].to_list()
print(countr)

In [ ]:
standard_names = coco.convert(names=countr, to='name_short')
print(standard_names)

In [ ]:
data_tuples = list(zip(countr, standard_names))
data_tuples

#df_countries = pd.DataFrame(standard_names)
#print (df_countries)

In [ ]:
dic = dict(data_tuples)
dic

In [ ]:
# substitute values
covid_new_df.loc[:,'Country/Region'].replace(to_replace = dic.keys(), value = dic.values() , inplace=True)
covid_new_df.head()

In [ ]:
covid_new_df["Country/Region"].value_counts()
countr2= covid_new_df['Country/Region'].to_list()
print(countr2)

In [ ]:
standard_names2 = coco.convert(names=countr2, to='continent')
print(standard_names2)

In [ ]:
data_tuples2 = list(zip(countr2, standard_names2))
data_tuples2
dic2 = dict(data_tuples2)
dic2

In [ ]:
#duplicate country's column

covid_new_df.insert(loc=1, column='Continent', value=['' for i in range(covid_new_df.shape[0])])

In [ ]:
#new_df['Continent'] = new_df['Continent'].fillna(new_df[])
#new_df.loc[new_df['Continent'].isnull(), 'Continent'] = new_df['Country/Region']
covid_new_df.loc[:,"Continent"] = countr2
covid_new_df.head()

In [ ]:
# substitute values
covid_new_df['Continent'].replace(to_replace = dic2.keys(), value = dic2.values() , inplace=True)
covid_new_df.head()

In [ ]:
#save it
covid_new_df.to_csv('C_Corona.csv')

In [ ]:
covid_new_df.shape

### Include Latitude and Longitude

In [21]:
# adding lat and long
centroids = pd.read_csv("world_country_and_usa_states_latitude_and_longitude_values.csv")
covid_new_df = pd.read_csv('C_Corona.csv')
centroids.columns

Index(['country_code', 'latitude', 'longitude', 'country', 'usa_state_code',
       'usa_state_latitude', 'usa_state_longitude', 'usa_state'],
      dtype='object')

In [22]:
centroids.drop(['country_code','usa_state_code',
       'usa_state_latitude', 'usa_state_longitude', 'usa_state'], axis =1, inplace=True)
centroids.head()

    latitude  longitude               country
0  42.546245   1.601554               Andorra
1  23.424076  53.847818  United Arab Emirates
2  33.939110  67.709953           Afghanistan
3  17.060816 -61.796428   Antigua and Barbuda
4  18.220554 -63.068615              Anguilla

In [23]:
centroids["country"].value_counts()

British Indian Ocean Territory    1
Greece                            1
Bouvet Island                     1
Morocco                           1
Tanzania                          1
                                 ..
Malaysia                          1
Ukraine                           1
Gibraltar                         1
Swaziland                         1
Oman                              1
Name: country, Length: 245, dtype: int64

In [24]:
centroids["country"] = centroids["country"].replace({"Congo [Republic]": "Congo"})
#WARNING:root:Netherlands Antilles not found in regex
#WARNING:root:Congo [Republic] not found in regex

In [25]:
centroids = centroids[centroids["country"] != "Netherlands Antilles"]

In [26]:
countr3= centroids["country"].to_list()
print(countr3)

['Andorra', 'United Arab Emirates', 'Afghanistan', 'Antigua and Barbuda', 'Anguilla', 'Albania', 'Armenia', 'Angola', 'Antarctica', 'Argentina', 'American Samoa', 'Austria', 'Australia', 'Aruba', 'Azerbaijan', 'Bosnia and Herzegovina', 'Barbados', 'Bangladesh', 'Belgium', 'Burkina Faso', 'Bulgaria', 'Bahrain', 'Burundi', 'Benin', 'Bermuda', 'Brunei', 'Bolivia', 'Brazil', 'Bahamas', 'Bhutan', 'Bouvet Island', 'Botswana', 'Belarus', 'Belize', 'Canada', 'Cocos [Keeling] Islands', 'Congo [DRC]', 'Central African Republic', 'Congo', 'Switzerland', "Côte d'Ivoire", 'Cook Islands', 'Chile', 'Cameroon', 'China', 'Colombia', 'Costa Rica', 'Cuba', 'Cape Verde', 'Christmas Island', 'Cyprus', 'Czech Republic', 'Germany', 'Djibouti', 'Denmark', 'Dominica', 'Dominican Republic', 'Algeria', 'Ecuador', 'Estonia', 'Egypt', 'Western Sahara', 'Eritrea', 'Spain', 'Ethiopia', 'Finland', 'Fiji', 'Falkland Islands [Islas Malvinas]', 'Micronesia', 'Faroe Islands', 'France', 'Gabon', 'United Kingdom', 'Grenada', 'Georgia', 'French Guiana', 'Guernsey', 'Ghana', 'Gibraltar', 'Greenland', 'Gambia', 'Guinea', 'Guadeloupe', 'Equatorial Guinea', 'Greece', 'South Georgia and the South Sandwich Islands', 'Guatemala', 'Guam', 'Guinea-Bissau', 'Guyana', 'Gaza Strip', 'Hong Kong', 'Heard Island and McDonald Islands', 'Honduras', 'Croatia', 'Haiti', 'Hungary', 'Indonesia', 'Ireland', 'Israel', 'Isle of Man', 'India', 'British Indian Ocean Territory', 'Iraq', 'Iran', 'Iceland', 'Italy', 'Jersey', 'Jamaica', 'Jordan', 'Japan', 'Kenya', 'Kyrgyzstan', 'Cambodia', 'Kiribati', 'Comoros', 'Saint Kitts and Nevis', 'North Korea', 'South Korea', 'Kuwait', 'Cayman Islands', 'Kazakhstan', 'Laos', 'Lebanon', 'Saint Lucia', 'Liechtenstein', 'Sri Lanka', 'Liberia', 'Lesotho', 'Lithuania', 'Luxembourg', 'Latvia', 'Libya', 'Morocco', 'Monaco', 'Moldova', 'Montenegro', 'Madagascar', 'Marshall Islands', 'Macedonia [FYROM]', 'Mali', 'Myanmar [Burma]', 'Mongolia', 'Macau', 'Northern Mariana Islands', 'Martinique', 'Mauritania', 'Montserrat', 'Malta', 'Mauritius', 'Maldives', 'Malawi', 'Mexico', 'Malaysia', 'Mozambique', 'Namibia', 'New Caledonia', 'Niger', 'Norfolk Island', 'Nigeria', 'Nicaragua', 'Netherlands', 'Norway', 'Nepal', 'Nauru', 'Niue', 'New Zealand', 'Oman', 'Panama', 'Peru', 'French Polynesia', 'Papua New Guinea', 'Philippines', 'Pakistan', 'Poland', 'Saint Pierre and Miquelon', 'Pitcairn Islands', 'Puerto Rico', 'Palestinian Territories', 'Portugal', 'Palau', 'Paraguay', 'Qatar', 'Réunion', 'Romania', 'Serbia', 'Russia', 'Rwanda', 'Saudi Arabia', 'Solomon Islands', 'Seychelles', 'Sudan', 'Sweden', 'Singapore', 'Saint Helena', 'Slovenia', 'Svalbard and Jan Mayen', 'Slovakia', 'Sierra Leone', 'San Marino', 'Senegal', 'Somalia', 'Suriname', 'São Tomé and Príncipe', 'El Salvador', 'Syria', 'Swaziland', 'Turks and Caicos Islands', 'Chad', 'French Southern Territories', 'Togo', 'Thailand', 'Tajikistan', 'Tokelau', 'Timor-Leste', 'Turkmenistan', 'Tunisia', 'Tonga', 'Turkey', 'Trinidad and Tobago', 'Tuvalu', 'Taiwan', 'Tanzania', 'Ukraine', 'Uganda', 'U.S. Minor Outlying Islands', 'United States', 'Uruguay', 'Uzbekistan', 'Vatican City', 'Saint Vincent and the Grenadines', 'Venezuela', 'British Virgin Islands', 'U.S. Virgin Islands', 'Vietnam', 'Vanuatu', 'Wallis and Futuna', 'Samoa', 'Kosovo', 'Yemen', 'Mayotte', 'South Africa', 'Zambia', 'Zimbabwe']

In [27]:
standard_names3 = coco.convert(names=countr3, to='name_short')
print(standard_names3)

['Andorra', 'United Arab Emirates', 'Afghanistan', 'Antigua and Barbuda', 'Anguilla', 'Albania', 'Armenia', 'Angola', 'Antarctica', 'Argentina', 'American Samoa', 'Austria', 'Australia', 'Aruba', 'Azerbaijan', 'Bosnia and Herzegovina', 'Barbados', 'Bangladesh', 'Belgium', 'Burkina Faso', 'Bulgaria', 'Bahrain', 'Burundi', 'Benin', 'Bermuda', 'Brunei Darussalam', 'Bolivia', 'Brazil', 'Bahamas', 'Bhutan', 'Bouvet Island', 'Botswana', 'Belarus', 'Belize', 'Canada', 'Cocos (Keeling) Islands', 'DR Congo', 'Central African Republic', 'Congo Republic', 'Switzerland', "Cote d'Ivoire", 'Cook Islands', 'Chile', 'Cameroon', 'China', 'Colombia', 'Costa Rica', 'Cuba', 'Cabo Verde', 'Christmas Island', 'Cyprus', 'Czech Republic', 'Germany', 'Djibouti', 'Denmark', 'Dominica', 'Dominican Republic', 'Algeria', 'Ecuador', 'Estonia', 'Egypt', 'Western Sahara', 'Eritrea', 'Spain', 'Ethiopia', 'Finland', 'Fiji', 'Falkland Islands', 'Micronesia, Fed. Sts.', 'Faeroe Islands', 'France', 'Gabon', 'United Kingdom', 'Grenada', 'Georgia', 'French Guiana', 'Guernsey', 'Ghana', 'Gibraltar', 'Greenland', 'Gambia', 'Guinea', 'Guadeloupe', 'Equatorial Guinea', 'Greece', 'South Georgia and South Sandwich Is.', 'Guatemala', 'Guam', 'Guinea-Bissau', 'Guyana', 'Palestine', 'Hong Kong', 'Heard and McDonald Islands', 'Honduras', 'Croatia', 'Haiti', 'Hungary', 'Indonesia', 'Ireland', 'Israel', 'Isle of Man', 'India', 'British Indian Ocean Territory', 'Iraq', 'Iran', 'Iceland', 'Italy', 'Jersey', 'Jamaica', 'Jordan', 'Japan', 'Kenya', 'Kyrgyz Republic', 'Cambodia', 'Kiribati', 'Comoros', 'St. Kitts and Nevis', 'North Korea', 'South Korea', 'Kuwait', 'Cayman Islands', 'Kazakhstan', 'Laos', 'Lebanon', 'St. Lucia', 'Liechtenstein', 'Sri Lanka', 'Liberia', 'Lesotho', 'Lithuania', 'Luxembourg', 'Latvia', 'Libya', 'Morocco', 'Monaco', 'Moldova', 'Montenegro', 'Madagascar', 'Marshall Islands', 'Macedonia', 'Mali', 'Myanmar', 'Mongolia', 'Macao', 'Northern Mariana Islands', 'Martinique', 'Mauritania', 'Montserrat', 'Malta', 'Mauritius', 'Maldives', 'Malawi', 'Mexico', 'Malaysia', 'Mozambique', 'Namibia', 'New Caledonia', 'Niger', 'Norfolk Island', 'Nigeria', 'Nicaragua', 'Netherlands', 'Norway', 'Nepal', 'Nauru', 'Niue', 'New Zealand', 'Oman', 'Panama', 'Peru', 'French Polynesia', 'Papua New Guinea', 'Philippines', 'Pakistan', 'Poland', 'St. Pierre and Miquelon', 'Pitcairn', 'Puerto Rico', 'Palestine', 'Portugal', 'Palau', 'Paraguay', 'Qatar', 'Reunion', 'Romania', 'Serbia', 'Russia', 'Rwanda', 'Saudi Arabia', 'Solomon Islands', 'Seychelles', 'Sudan', 'Sweden', 'Singapore', 'St. Helena', 'Slovenia', 'Svalbard and Jan Mayen Islands', 'Slovakia', 'Sierra Leone', 'San Marino', 'Senegal', 'Somalia', 'Suriname', 'Sao Tome and Principe', 'El Salvador', 'Syria', 'Eswatini', 'Turks and Caicos Islands', 'Chad', 'French Southern Territories', 'Togo', 'Thailand', 'Tajikistan', 'Tokelau', 'Timor-Leste', 'Turkmenistan', 'Tunisia', 'Tonga', 'Turkey', 'Trinidad and Tobago', 'Tuvalu', 'Taiwan', 'Tanzania', 'Ukraine', 'Uganda', 'United States Minor Outlying Islands', 'United States', 'Uruguay', 'Uzbekistan', 'Vatican', 'St. Vincent and the Grenadines', 'Venezuela', 'British Virgin Islands', 'United States Virgin Islands', 'Vietnam', 'Vanuatu', 'Wallis and Futuna Islands', 'Samoa', 'Kosovo', 'Yemen', 'Mayotte', 'South Africa', 'Zambia', 'Zimbabwe']

In [28]:
data_tuples3 = list(zip(countr3, standard_names3))
dic3 = dict(data_tuples3)
dic3

{'Andorra': 'Andorra',
 'United Arab Emirates': 'United Arab Emirates',
 'Afghanistan': 'Afghanistan',
 'Antigua and Barbuda': 'Antigua and Barbuda',
 'Anguilla': 'Anguilla',
 'Albania': 'Albania',
 'Armenia': 'Armenia',
 'Angola': 'Angola',
 'Antarctica': 'Antarctica',
 'Argentina': 'Argentina',
 'American Samoa': 'American Samoa',
 'Austria': 'Austria',
 'Australia': 'Australia',
 'Aruba': 'Aruba',
 'Azerbaijan': 'Azerbaijan',
 'Bosnia and Herzegovina': 'Bosnia and Herzegovina',
 'Barbados': 'Barbados',
 'Bangladesh': 'Bangladesh',
 'Belgium': 'Belgium',
 'Burkina Faso': 'Burkina Faso',
 'Bulgaria': 'Bulgaria',
 'Bahrain': 'Bahrain',
 'Burundi': 'Burundi',
 'Benin': 'Benin',
 'Bermuda': 'Bermuda',
 'Brunei': 'Brunei Darussalam',
 'Bolivia': 'Bolivia',
 'Brazil': 'Brazil',
 'Bahamas': 'Bahamas',
 'Bhutan': 'Bhutan',
 'Bouvet Island': 'Bouvet Island',
 'Botswana': 'Botswana',
 'Belarus': 'Belarus',
 'Belize': 'Belize',
 'Canada': 'Canada',
 'Cocos [Keeling] Islands': 'Cocos (Keeling) Islands',
 'Congo [DRC]': 'DR Congo',
 'Central African Republic': 'Central African Republic',
 'Congo': 'Congo Republic',
 'Switzerland': 'Switzerland',
 "Côte d'Ivoire": "Cote d'Ivoire",
 'Cook Islands': 'Cook Islands',
 'Chile': 'Chile',
 'Cameroon': 'Cameroon',
 'China': 'China',
 'Colombia': 'Colombia',
 'Costa Rica': 'Costa Rica',
 'Cuba': 'Cuba',
 'Cape Verde': 'Cabo Verde',
 'Christmas Island': 'Christmas Island',
 'Cyprus': 'Cyprus',
 'Czech Republic': 'Czech Republic',
 'Germany': 'Germany',
 'Djibouti': 'Djibouti',
 'Denmark': 'Denmark',
 'Dominica': 'Dominica',
 'Dominican Republic': 'Dominican Republic',
 'Algeria': 'Algeria',
 'Ecuador': 'Ecuador',
 'Estonia': 'Estonia',
 'Egypt': 'Egypt',
 'Western Sahara': 'Western Sahara',
 'Eritrea': 'Eritrea',
 'Spain': 'Spain',
 'Ethiopia': 'Ethiopia',
 'Finland': 'Finland',
 'Fiji': 'Fiji',
 'Falkland Islands [Islas Malvinas]': 'Falkland Islands',
 'Micronesia': 'Micronesia, Fed. Sts.',
 'Faroe Islands': 'Faeroe Islands',
 'France': 'France',
 'Gabon': 'Gabon',
 'United Kingdom': 'United Kingdom',
 'Grenada': 'Grenada',
 'Georgia': 'Georgia',
 'French Guiana': 'French Guiana',
 'Guernsey': 'Guernsey',
 'Ghana': 'Ghana',
 'Gibraltar': 'Gibraltar',
 'Greenland': 'Greenland',
 'Gambia': 'Gambia',
 'Guinea': 'Guinea',
 'Guadeloupe': 'Guadeloupe',
 'Equatorial Guinea': 'Equatorial Guinea',
 'Greece': 'Greece',
 'South Georgia and the South Sandwich Islands': 'South Georgia and South Sandwich Is.',
 'Guatemala': 'Guatemala',
 'Guam': 'Guam',
 'Guinea-Bissau': 'Guinea-Bissau',
 'Guyana': 'Guyana',
 'Gaza Strip': 'Palestine',
 'Hong Kong': 'Hong Kong',
 'Heard Island and McDonald Islands': 'Heard and McDonald Islands',
 'Honduras': 'Honduras',
 'Croatia': 'Croatia',
 'Haiti': 'Haiti',
 'Hungary': 'Hungary',
 'Indonesia': 'Indonesia',
 'Ireland': 'Ireland',
 'Israel': 'Israel',
 'Isle of Man': 'Isle of Man',
 'India': 'India',
 'British Indian Ocean Territory': 'British Indian Ocean Territory',
 'Iraq': 'Iraq',
 'Iran': 'Iran',
 'Iceland': 'Iceland',
 'Italy': 'Italy',
 'Jersey': 'Jersey',
 'Jamaica': 'Jamaica',
 'Jordan': 'Jordan',
 'Japan': 'Japan',
 'Kenya': 'Kenya',
 'Kyrgyzstan': 'Kyrgyz Republic',
 'Cambodia': 'Cambodia',
 'Kiribati': 'Kiribati',
 'Comoros': 'Comoros',
 'Saint Kitts and Nevis': 'St. Kitts and Nevis',
 'North Korea': 'North Korea',
 'South Korea': 'South Korea',
 'Kuwait': 'Kuwait',
 'Cayman Islands': 'Cayman Islands',
 'Kazakhstan': 'Kazakhstan',
 'Laos': 'Laos',
 'Lebanon': 'Lebanon',
 'Saint Lucia': 'St. Lucia',
 'Liechtenstein': 'Liechtenstein',
 'Sri Lanka': 'Sri Lanka',
 'Liberia': 'Liberia',
 'Lesotho': 'Lesotho',
 'Lithuania': 'Lithuania',
 'Luxembourg': 'Luxembourg',
 'Latvia': 'Latvia',
 'Libya': 'Libya',
 'Morocco': 'Morocco',
 'Monaco': 'Monaco',
 'Moldova': 'Moldova',
 'Montenegro': 'Montenegro',
 'Madagascar': 'Madagascar',
 'Marshall Islands': 'Marshall Islands',
 'Macedonia [FYROM]': 'Macedonia',
 'Mali': 'Mali',
 'Myanmar [Burma]': 'Myanmar',
 'Mongolia': 'Mongolia',
 'Macau': 'Macao',
 'Northern Mariana Islands': 'Northern Mariana Islands',
 'Martinique': 'Martinique',
 'Mauritania': 'Mauritania',
 'Montserrat': 'Montserrat',
 'Malta': 'Malta',
 'Mauritius': 'Mauritius',
 'Maldives': 'Maldives',
 'Malawi': 'Malawi',
 'Mexico': 'Mexico',
 'Malaysia': 'Malaysia',
 'Mozambique': 'Mozambique',
 'Namibia': 'Namibia',
 'New Caledonia': 'New Caledonia',
 'Niger': 'Niger',
 'Norfolk Island': 'Norfolk Island',
 'Nigeria': 'Nigeria',
 'Nicaragua': 'Nicaragua',
 'Netherlands': 'Netherlands',
 'Norway': 'Norway',
 'Nepal': 'Nepal',
 'Nauru': 'Nauru',
 'Niue': 'Niue',
 'New Zealand': 'New Zealand',
 'Oman': 'Oman',
 'Panama': 'Panama',
 'Peru': 'Peru',
 'French Polynesia': 'French Polynesia',
 'Papua New Guinea': 'Papua New Guinea',
 'Philippines': 'Philippines',
 'Pakistan': 'Pakistan',
 'Poland': 'Poland',
 'Saint Pierre and Miquelon': 'St. Pierre and Miquelon',
 'Pitcairn Islands': 'Pitcairn',
 'Puerto Rico': 'Puerto Rico',
 'Palestinian Territories': 'Palestine',
 'Portugal': 'Portugal',
 'Palau': 'Palau',
 'Paraguay': 'Paraguay',
 'Qatar': 'Qatar',
 'Réunion': 'Reunion',
 'Romania': 'Romania',
 'Serbia': 'Serbia',
 'Russia': 'Russia',
 'Rwanda': 'Rwanda',
 'Saudi Arabia': 'Saudi Arabia',
 'Solomon Islands': 'Solomon Islands',
 'Seychelles': 'Seychelles',
 'Sudan': 'Sudan',
 'Sweden': 'Sweden',
 'Singapore': 'Singapore',
 'Saint Helena': 'St. Helena',
 'Slovenia': 'Slovenia',
 'Svalbard and Jan Mayen': 'Svalbard and Jan Mayen Islands',
 'Slovakia': 'Slovakia',
 'Sierra Leone': 'Sierra Leone',
 'San Marino': 'San Marino',
 'Senegal': 'Senegal',
 'Somalia': 'Somalia',
 'Suriname': 'Suriname',
 'São Tomé and Príncipe': 'Sao Tome and Principe',
 'El Salvador': 'El Salvador',
 'Syria': 'Syria',
 'Swaziland': 'Eswatini',
 'Turks and Caicos Islands': 'Turks and Caicos Islands',
 'Chad': 'Chad',
 'French Southern Territories': 'French Southern Territories',
 'Togo': 'Togo',
 'Thailand': 'Thailand',
 'Tajikistan': 'Tajikistan',
 'Tokelau': 'Tokelau',
 'Timor-Leste': 'Timor-Leste',
 'Turkmenistan': 'Turkmenistan',
 'Tunisia': 'Tunisia',
 'Tonga': 'Tonga',
 'Turkey': 'Turkey',
 'Trinidad and Tobago': 'Trinidad and Tobago',
 'Tuvalu': 'Tuvalu',
 'Taiwan': 'Taiwan',
 'Tanzania': 'Tanzania',
 'Ukraine': 'Ukraine',
 'Uganda': 'Uganda',
 'U.S. Minor Outlying Islands': 'United States Minor Outlying Islands',
 'United States': 'United States',
 'Uruguay': 'Uruguay',
 'Uzbekistan': 'Uzbekistan',
 'Vatican City': 'Vatican',
 'Saint Vincent and the Grenadines': 'St. Vincent and the Grenadines',
 'Venezuela': 'Venezuela',
 'British Virgin Islands': 'British Virgin Islands',
 'U.S. Virgin Islands': 'United States Virgin Islands',
 'Vietnam': 'Vietnam',
 'Vanuatu': 'Vanuatu',
 'Wallis and Futuna': 'Wallis and Futuna Islands',
 'Samoa': 'Samoa',
 'Kosovo': 'Kosovo',
 'Yemen': 'Yemen',
 'Mayotte': 'Mayotte',
 'South Africa': 'South Africa',
 'Zambia': 'Zambia',
 'Zimbabwe': 'Zimbabwe'}

In [29]:
centroids.loc[:,"country"].replace(to_replace = dic3.keys(), value = dic3.values() , inplace=True)
centroids.head()

    latitude  longitude               country
0  42.546245   1.601554               Andorra
1  23.424076  53.847818  United Arab Emirates
2  33.939110  67.709953           Afghanistan
3  17.060816 -61.796428   Antigua and Barbuda
4  18.220554 -63.068615              Anguilla

In [30]:
centroids =centroids.drop_duplicates(subset=['country'], keep='last')
centroids.shape

(243, 3)

<b>Joining two dataframes to have the Continent, Logitude and Latitude information in the dataframe</b>

In [31]:
#merging the columns Lon and Lat
#covid_complete_df=pd.merge(covid_new_df,centroids[["Country/Region", "Longitude"]], how="left", left_on = 'Country/Region', right_on = 'sovereignt').drop('sovereignt')
covid_complete_df = pd.merge(left=covid_new_df, right=centroids, how='left', left_on='Country/Region', right_on='country').set_index('ObservationDate')
del covid_complete_df["country"]
#del covid_complete_df["Last Update"]
#del covid_complete_df["Unnamed: 0"]

In [32]:
covid_complete_df.head()

,Country/Region,Continent,Confirmed,Deaths,Recovered,latitude,longitude
ObservationDate,,,,,,,
2020-01-22,China,Asia,547.0,17.0,28.0,35.861660,104.195397
2020-01-22,Hong Kong,Asia,0.0,0.0,0.0,22.396428,114.109497
2020-01-22,Japan,Asia,2.0,0.0,0.0,36.204824,138.252924
2020-01-22,Macao,Asia,1.0,0.0,0.0,22.198745,113.543873
2020-01-22,South Korea,Asia,1.0,0.0,0.0,35.907757,127.766922

In [33]:
print(covid_complete_df.shape)
print(covid_new_df.shape)

(3872, 7)
(3872, 6)

In [34]:
covid_complete_df.isnull().sum()

Country/Region     0
Continent          0
Confirmed          0
Deaths             0
Recovered          0
latitude          11
longitude         11
dtype: int64

In [35]:
nullcheck_df = covid_complete_df[covid_complete_df.isna().any(axis=1)]
nullcheck_df.head(11)
#St. Barths , Saint-Martin, Curacao

,Country/Region,Continent,Confirmed,Deaths,Recovered,latitude,longitude
ObservationDate,,,,,,,
2020-03-04,St. Barths,America,3.0,0.0,0.0,NaN,NaN
2020-03-05,St. Barths,America,3.0,0.0,0.0,NaN,NaN
2020-03-06,St. Barths,America,3.0,0.0,0.0,NaN,NaN
2020-03-07,St. Barths,America,3.0,0.0,0.0,NaN,NaN
2020-03-08,St. Barths,America,3.0,0.0,0.0,NaN,NaN
2020-03-09,Saint-Martin,America,2.0,0.0,0.0,NaN,NaN
2020-03-09,St. Barths,America,1.0,0.0,0.0,NaN,NaN
2020-03-10,Saint-Martin,America,2.0,0.0,0.0,NaN,NaN
2020-03-10,St. Barths,America,1.0,0.0,0.0,NaN,NaN
2020-03-14,Curacao,America,1.0,0.0,0.0,NaN,NaN
2020-03-15,Curacao,America,1.0,0.0,0.0,NaN,NaN

In [36]:
covid_complete_df.rename(columns={"Country/Region": "Country", 
                       "Province/State":"Province_State"  
                        }, inplace =True)
covid_complete_df.columns

Index(['Country', 'Continent', 'Confirmed', 'Deaths', 'Recovered', 'latitude',
       'longitude'],
      dtype='object')

##### Taking care of missing long and lat by adding it manually

In [37]:
covid_complete_df.loc[covid_complete_df['Country'] == 'St. Barths', 'latitude'] = 117.9139
covid_complete_df.loc[covid_complete_df['Country'] == 'St. Barths', 'longitude'] = -62.8339

covid_complete_df.loc[covid_complete_df['Country'] == 'Saint-Martin', 'latitude'] = 18.073099
covid_complete_df.loc[covid_complete_df['Country'] == 'Saint-Martin', 'longitude'] = -63.082199

covid_complete_df.loc[covid_complete_df['Country'] == 'Curacao', 'latitude'] = 12.169570
covid_complete_df.loc[covid_complete_df['Country'] == 'Curacao', 'longitude'] = -68.990021

In [38]:
print(covid_complete_df.shape)
print(covid_new_df.shape)

(3872, 7)
(3872, 6)

In [39]:
covid_complete_df.isnull().sum()

Country      0
Continent    0
Confirmed    0
Deaths       0
Recovered    0
latitude     0
longitude    0
dtype: int64

In [40]:
covid_complete_df.to_csv('C_L_Corona.csv')

##### Adding new columns

In [41]:
covid_df = covid_complete_df.copy()

In [42]:
covid_df['Active Cases'] = covid_df['Confirmed'] - covid_df['Deaths'] - covid_df['Recovered']
covid_df['Active Cases'].astype(int)
covid_df.head()

,Country,Continent,Confirmed,Deaths,Recovered,latitude,longitude,Active Cases
ObservationDate,,,,,,,,
2020-01-22,China,Asia,547.0,17.0,28.0,35.861660,104.195397,502.0
2020-01-22,Hong Kong,Asia,0.0,0.0,0.0,22.396428,114.109497,0.0
2020-01-22,Japan,Asia,2.0,0.0,0.0,36.204824,138.252924,2.0
2020-01-22,Macao,Asia,1.0,0.0,0.0,22.198745,113.543873,1.0
2020-01-22,South Korea,Asia,1.0,0.0,0.0,35.907757,127.766922,1.0

In [43]:
#https://www.kaggle.com/fernandol/countries-of-the-world
countries = pd.read_csv("countries of the world.csv")
countries.head()

,Country,Region,Population,Area (sq. mi.),Pop. Density (per sq. mi.),Coastline (coast/area ratio),Net migration,Infant mortality (per 1000 births),GDP ($ per capita),Literacy (%),Phones (per 1000),Arable (%),Crops (%),Other (%),Climate,Birthrate,Deathrate,Agriculture,Industry,Service
0,Afghanistan,ASIA (EX. NEAR EAST),31056997,647500,"48,0","0,00","23,06","163,07",700.0,"36,0","3,2","12,13","0,22","87,65",1,"46,6","20,34","0,38","0,24","0,38"
1,Albania,EASTERN EUROPE,3581655,28748,"124,6","1,26","-4,93","21,52",4500.0,"86,5","71,2","21,09","4,42","74,49",3,"15,11","5,22","0,232","0,188","0,579"
2,Algeria,NORTHERN AFRICA,32930091,2381740,"13,8","0,04","-0,39",31,6000.0,"70,0","78,1","3,22","0,25","96,53",1,"17,14","4,61","0,101","0,6","0,298"
3,American Samoa,OCEANIA,57794,199,"290,4","58,29","-20,71","9,27",8000.0,"97,0","259,5",10,15,75,2,"22,46","3,27",NaN,NaN,NaN
4,Andorra,WESTERN EUROPE,71201,468,"152,1","0,00","6,6","4,05",19000.0,"100,0","497,2","2,22",0,"97,78",3,"8,71","6,25",NaN,NaN,NaN

In [44]:
countries.columns

Index(['Country', 'Region', 'Population', 'Area (sq. mi.)',
       'Pop. Density (per sq. mi.)', 'Coastline (coast/area ratio)',
       'Net migration', 'Infant mortality (per 1000 births)',
       'GDP ($ per capita)', 'Literacy (%)', 'Phones (per 1000)', 'Arable (%)',
       'Crops (%)', 'Other (%)', 'Climate', 'Birthrate', 'Deathrate',
       'Agriculture', 'Industry', 'Service'],
      dtype='object')

##### Deleting unnecessary columns

In [45]:
del countries["Climate"]
del countries["Other (%)"]
del countries["Coastline (coast/area ratio)"]
del countries['Arable (%)']
del countries['Agriculture']
del countries['Industry']
del countries['Service']
del countries['Phones (per 1000)']
del countries['Crops (%)']
del countries['Region']
del countries['Infant mortality (per 1000 births)']
del countries['Literacy (%)']
del countries['Birthrate']
del countries['Deathrate']
countries.head()

,Country,Population,Area (sq. mi.),Pop. Density (per sq. mi.),Net migration,GDP ($ per capita)
0,Afghanistan,31056997,647500,"48,0","23,06",700.0
1,Albania,3581655,28748,"124,6","-4,93",4500.0
2,Algeria,32930091,2381740,"13,8","-0,39",6000.0
3,American Samoa,57794,199,"290,4","-20,71",8000.0
4,Andorra,71201,468,"152,1","6,6",19000.0

In [46]:
country= countries['Country'].to_list()
print(country)

['Afghanistan ', 'Albania ', 'Algeria ', 'American Samoa ', 'Andorra ', 'Angola ', 'Anguilla ', 'Antigua & Barbuda ', 'Argentina ', 'Armenia ', 'Aruba ', 'Australia ', 'Austria ', 'Azerbaijan ', 'Bahamas, The ', 'Bahrain ', 'Bangladesh ', 'Barbados ', 'Belarus ', 'Belgium ', 'Belize ', 'Benin ', 'Bermuda ', 'Bhutan ', 'Bolivia ', 'Bosnia & Herzegovina ', 'Botswana ', 'Brazil ', 'British Virgin Is. ', 'Brunei ', 'Bulgaria ', 'Burkina Faso ', 'Burma ', 'Burundi ', 'Cambodia ', 'Cameroon ', 'Canada ', 'Cape Verde ', 'Cayman Islands ', 'Central African Rep. ', 'Chad ', 'Chile ', 'China ', 'Colombia ', 'Comoros ', 'Congo, Dem. Rep. ', 'Congo, Repub. of the ', 'Cook Islands ', 'Costa Rica ', "Cote d'Ivoire ", 'Croatia ', 'Cuba ', 'Cyprus ', 'Czech Republic ', 'Denmark ', 'Djibouti ', 'Dominica ', 'Dominican Republic ', 'East Timor ', 'Ecuador ', 'Egypt ', 'El Salvador ', 'Equatorial Guinea ', 'Eritrea ', 'Estonia ', 'Ethiopia ', 'Faroe Islands ', 'Fiji ', 'Finland ', 'France ', 'French Guiana ', 'French Polynesia ', 'Gabon ', 'Gambia, The ', 'Gaza Strip ', 'Georgia ', 'Germany ', 'Ghana ', 'Gibraltar ', 'Greece ', 'Greenland ', 'Grenada ', 'Guadeloupe ', 'Guam ', 'Guatemala ', 'Guernsey ', 'Guinea ', 'Guinea-Bissau ', 'Guyana ', 'Haiti ', 'Honduras ', 'Hong Kong ', 'Hungary ', 'Iceland ', 'India ', 'Indonesia ', 'Iran ', 'Iraq ', 'Ireland ', 'Isle of Man ', 'Israel ', 'Italy ', 'Jamaica ', 'Japan ', 'Jersey ', 'Jordan ', 'Kazakhstan ', 'Kenya ', 'Kiribati ', 'Korea, North ', 'Korea, South ', 'Kuwait ', 'Kyrgyzstan ', 'Laos ', 'Latvia ', 'Lebanon ', 'Lesotho ', 'Liberia ', 'Libya ', 'Liechtenstein ', 'Lithuania ', 'Luxembourg ', 'Macau ', 'Macedonia ', 'Madagascar ', 'Malawi ', 'Malaysia ', 'Maldives ', 'Mali ', 'Malta ', 'Marshall Islands ', 'Martinique ', 'Mauritania ', 'Mauritius ', 'Mayotte ', 'Mexico ', 'Micronesia, Fed. St. ', 'Moldova ', 'Monaco ', 'Mongolia ', 'Montserrat ', 'Morocco ', 'Mozambique ', 'Namibia ', 'Nauru ', 'Nepal ', 'Netherlands ', 'Netherlands Antilles ', 'New Caledonia ', 'New Zealand ', 'Nicaragua ', 'Niger ', 'Nigeria ', 'N. Mariana Islands ', 'Norway ', 'Oman ', 'Pakistan ', 'Palau ', 'Panama ', 'Papua New Guinea ', 'Paraguay ', 'Peru ', 'Philippines ', 'Poland ', 'Portugal ', 'Puerto Rico ', 'Qatar ', 'Reunion ', 'Romania ', 'Russia ', 'Rwanda ', 'Saint Helena ', 'Saint Kitts & Nevis ', 'Saint Lucia ', 'St Pierre & Miquelon ', 'Saint Vincent and the Grenadines ', 'Samoa ', 'San Marino ', 'Sao Tome & Principe ', 'Saudi Arabia ', 'Senegal ', 'Serbia ', 'Seychelles ', 'Sierra Leone ', 'Singapore ', 'Slovakia ', 'Slovenia ', 'Solomon Islands ', 'Somalia ', 'South Africa ', 'Spain ', 'Sri Lanka ', 'Sudan ', 'Suriname ', 'Swaziland ', 'Sweden ', 'Switzerland ', 'Syria ', 'Taiwan ', 'Tajikistan ', 'Tanzania ', 'Thailand ', 'Togo ', 'Tonga ', 'Trinidad & Tobago ', 'Tunisia ', 'Turkey ', 'Turkmenistan ', 'Turks & Caicos Is ', 'Tuvalu ', 'Uganda ', 'Ukraine ', 'United Arab Emirates ', 'United Kingdom ', 'United States ', 'Uruguay ', 'Uzbekistan ', 'Vanuatu ', 'Venezuela ', 'Vietnam ', 'Virgin Islands ', 'Wallis and Futuna ', 'West Bank ', 'Western Sahara ', 'Yemen ', 'Zambia ', 'Zimbabwe ']

In [47]:
#WARNING:root:Netherlands Antilles  not found in regex
#WARNING:root:Virgin Islands  not found in regex
country.remove("Netherlands Antilles ")
country.remove("Virgin Islands ")

In [48]:
standard_names = coco.convert(names=country, to='name_short')
print(standard_names)

['Afghanistan', 'Albania', 'Algeria', 'American Samoa', 'Andorra', 'Angola', 'Anguilla', 'Antigua and Barbuda', 'Argentina', 'Armenia', 'Aruba', 'Australia', 'Austria', 'Azerbaijan', 'Bahamas', 'Bahrain', 'Bangladesh', 'Barbados', 'Belarus', 'Belgium', 'Belize', 'Benin', 'Bermuda', 'Bhutan', 'Bolivia', 'Bosnia and Herzegovina', 'Botswana', 'Brazil', 'British Virgin Islands', 'Brunei Darussalam', 'Bulgaria', 'Burkina Faso', 'Myanmar', 'Burundi', 'Cambodia', 'Cameroon', 'Canada', 'Cabo Verde', 'Cayman Islands', 'Central African Republic', 'Chad', 'Chile', 'China', 'Colombia', 'Comoros', 'DR Congo', 'Congo Republic', 'Cook Islands', 'Costa Rica', "Cote d'Ivoire", 'Croatia', 'Cuba', 'Cyprus', 'Czech Republic', 'Denmark', 'Djibouti', 'Dominica', 'Dominican Republic', 'Timor-Leste', 'Ecuador', 'Egypt', 'El Salvador', 'Equatorial Guinea', 'Eritrea', 'Estonia', 'Ethiopia', 'Faeroe Islands', 'Fiji', 'Finland', 'France', 'French Guiana', 'French Polynesia', 'Gabon', 'Gambia', 'Palestine', 'Georgia', 'Germany', 'Ghana', 'Gibraltar', 'Greece', 'Greenland', 'Grenada', 'Guadeloupe', 'Guam', 'Guatemala', 'Guernsey', 'Guinea', 'Guinea-Bissau', 'Guyana', 'Haiti', 'Honduras', 'Hong Kong', 'Hungary', 'Iceland', 'India', 'Indonesia', 'Iran', 'Iraq', 'Ireland', 'Isle of Man', 'Israel', 'Italy', 'Jamaica', 'Japan', 'Jersey', 'Jordan', 'Kazakhstan', 'Kenya', 'Kiribati', 'North Korea', 'South Korea', 'Kuwait', 'Kyrgyz Republic', 'Laos', 'Latvia', 'Lebanon', 'Lesotho', 'Liberia', 'Libya', 'Liechtenstein', 'Lithuania', 'Luxembourg', 'Macao', 'Macedonia', 'Madagascar', 'Malawi', 'Malaysia', 'Maldives', 'Mali', 'Malta', 'Marshall Islands', 'Martinique', 'Mauritania', 'Mauritius', 'Mayotte', 'Mexico', 'Micronesia, Fed. Sts.', 'Moldova', 'Monaco', 'Mongolia', 'Montserrat', 'Morocco', 'Mozambique', 'Namibia', 'Nauru', 'Nepal', 'Netherlands', 'New Caledonia', 'New Zealand', 'Nicaragua', 'Niger', 'Nigeria', 'Northern Mariana Islands', 'Norway', 'Oman', 'Pakistan', 'Palau', 'Panama', 'Papua New Guinea', 'Paraguay', 'Peru', 'Philippines', 'Poland', 'Portugal', 'Puerto Rico', 'Qatar', 'Reunion', 'Romania', 'Russia', 'Rwanda', 'St. Helena', 'St. Kitts and Nevis', 'St. Lucia', 'St. Pierre and Miquelon', 'St. Vincent and the Grenadines', 'Samoa', 'San Marino', 'Sao Tome and Principe', 'Saudi Arabia', 'Senegal', 'Serbia', 'Seychelles', 'Sierra Leone', 'Singapore', 'Slovakia', 'Slovenia', 'Solomon Islands', 'Somalia', 'South Africa', 'Spain', 'Sri Lanka', 'Sudan', 'Suriname', 'Eswatini', 'Sweden', 'Switzerland', 'Syria', 'Taiwan', 'Tajikistan', 'Tanzania', 'Thailand', 'Togo', 'Tonga', 'Trinidad and Tobago', 'Tunisia', 'Turkey', 'Turkmenistan', 'Turks and Caicos Islands', 'Tuvalu', 'Uganda', 'Ukraine', 'United Arab Emirates', 'United Kingdom', 'United States', 'Uruguay', 'Uzbekistan', 'Vanuatu', 'Venezuela', 'Vietnam', 'Wallis and Futuna Islands', 'Palestine', 'Western Sahara', 'Yemen', 'Zambia', 'Zimbabwe']

In [49]:
data_tuples = list(zip(country, standard_names))
data_tuples
dic = dict(data_tuples)
dic

{'Afghanistan ': 'Afghanistan',
 'Albania ': 'Albania',
 'Algeria ': 'Algeria',
 'American Samoa ': 'American Samoa',
 'Andorra ': 'Andorra',
 'Angola ': 'Angola',
 'Anguilla ': 'Anguilla',
 'Antigua & Barbuda ': 'Antigua and Barbuda',
 'Argentina ': 'Argentina',
 'Armenia ': 'Armenia',
 'Aruba ': 'Aruba',
 'Australia ': 'Australia',
 'Austria ': 'Austria',
 'Azerbaijan ': 'Azerbaijan',
 'Bahamas, The ': 'Bahamas',
 'Bahrain ': 'Bahrain',
 'Bangladesh ': 'Bangladesh',
 'Barbados ': 'Barbados',
 'Belarus ': 'Belarus',
 'Belgium ': 'Belgium',
 'Belize ': 'Belize',
 'Benin ': 'Benin',
 'Bermuda ': 'Bermuda',
 'Bhutan ': 'Bhutan',
 'Bolivia ': 'Bolivia',
 'Bosnia & Herzegovina ': 'Bosnia and Herzegovina',
 'Botswana ': 'Botswana',
 'Brazil ': 'Brazil',
 'British Virgin Is. ': 'British Virgin Islands',
 'Brunei ': 'Brunei Darussalam',
 'Bulgaria ': 'Bulgaria',
 'Burkina Faso ': 'Burkina Faso',
 'Burma ': 'Myanmar',
 'Burundi ': 'Burundi',
 'Cambodia ': 'Cambodia',
 'Cameroon ': 'Cameroon',
 'Canada ': 'Canada',
 'Cape Verde ': 'Cabo Verde',
 'Cayman Islands ': 'Cayman Islands',
 'Central African Rep. ': 'Central African Republic',
 'Chad ': 'Chad',
 'Chile ': 'Chile',
 'China ': 'China',
 'Colombia ': 'Colombia',
 'Comoros ': 'Comoros',
 'Congo, Dem. Rep. ': 'DR Congo',
 'Congo, Repub. of the ': 'Congo Republic',
 'Cook Islands ': 'Cook Islands',
 'Costa Rica ': 'Costa Rica',
 "Cote d'Ivoire ": "Cote d'Ivoire",
 'Croatia ': 'Croatia',
 'Cuba ': 'Cuba',
 'Cyprus ': 'Cyprus',
 'Czech Republic ': 'Czech Republic',
 'Denmark ': 'Denmark',
 'Djibouti ': 'Djibouti',
 'Dominica ': 'Dominica',
 'Dominican Republic ': 'Dominican Republic',
 'East Timor ': 'Timor-Leste',
 'Ecuador ': 'Ecuador',
 'Egypt ': 'Egypt',
 'El Salvador ': 'El Salvador',
 'Equatorial Guinea ': 'Equatorial Guinea',
 'Eritrea ': 'Eritrea',
 'Estonia ': 'Estonia',
 'Ethiopia ': 'Ethiopia',
 'Faroe Islands ': 'Faeroe Islands',
 'Fiji ': 'Fiji',
 'Finland ': 'Finland',
 'France ': 'France',
 'French Guiana ': 'French Guiana',
 'French Polynesia ': 'French Polynesia',
 'Gabon ': 'Gabon',
 'Gambia, The ': 'Gambia',
 'Gaza Strip ': 'Palestine',
 'Georgia ': 'Georgia',
 'Germany ': 'Germany',
 'Ghana ': 'Ghana',
 'Gibraltar ': 'Gibraltar',
 'Greece ': 'Greece',
 'Greenland ': 'Greenland',
 'Grenada ': 'Grenada',
 'Guadeloupe ': 'Guadeloupe',
 'Guam ': 'Guam',
 'Guatemala ': 'Guatemala',
 'Guernsey ': 'Guernsey',
 'Guinea ': 'Guinea',
 'Guinea-Bissau ': 'Guinea-Bissau',
 'Guyana ': 'Guyana',
 'Haiti ': 'Haiti',
 'Honduras ': 'Honduras',
 'Hong Kong ': 'Hong Kong',
 'Hungary ': 'Hungary',
 'Iceland ': 'Iceland',
 'India ': 'India',
 'Indonesia ': 'Indonesia',
 'Iran ': 'Iran',
 'Iraq ': 'Iraq',
 'Ireland ': 'Ireland',
 'Isle of Man ': 'Isle of Man',
 'Israel ': 'Israel',
 'Italy ': 'Italy',
 'Jamaica ': 'Jamaica',
 'Japan ': 'Japan',
 'Jersey ': 'Jersey',
 'Jordan ': 'Jordan',
 'Kazakhstan ': 'Kazakhstan',
 'Kenya ': 'Kenya',
 'Kiribati ': 'Kiribati',
 'Korea, North ': 'North Korea',
 'Korea, South ': 'South Korea',
 'Kuwait ': 'Kuwait',
 'Kyrgyzstan ': 'Kyrgyz Republic',
 'Laos ': 'Laos',
 'Latvia ': 'Latvia',
 'Lebanon ': 'Lebanon',
 'Lesotho ': 'Lesotho',
 'Liberia ': 'Liberia',
 'Libya ': 'Libya',
 'Liechtenstein ': 'Liechtenstein',
 'Lithuania ': 'Lithuania',
 'Luxembourg ': 'Luxembourg',
 'Macau ': 'Macao',
 'Macedonia ': 'Macedonia',
 'Madagascar ': 'Madagascar',
 'Malawi ': 'Malawi',
 'Malaysia ': 'Malaysia',
 'Maldives ': 'Maldives',
 'Mali ': 'Mali',
 'Malta ': 'Malta',
 'Marshall Islands ': 'Marshall Islands',
 'Martinique ': 'Martinique',
 'Mauritania ': 'Mauritania',
 'Mauritius ': 'Mauritius',
 'Mayotte ': 'Mayotte',
 'Mexico ': 'Mexico',
 'Micronesia, Fed. St. ': 'Micronesia, Fed. Sts.',
 'Moldova ': 'Moldova',
 'Monaco ': 'Monaco',
 'Mongolia ': 'Mongolia',
 'Montserrat ': 'Montserrat',
 'Morocco ': 'Morocco',
 'Mozambique ': 'Mozambique',
 'Namibia ': 'Namibia',
 'Nauru ': 'Nauru',
 'Nepal ': 'Nepal',
 'Netherlands ': 'Netherlands',
 'New Caledonia ': 'New Caledonia',
 'New Zealand ': 'New Zealand',
 'Nicaragua ': 'Nicaragua',
 'Niger ': 'Niger',
 'Nigeria ': 'Nigeria',
 'N. Mariana Islands ': 'Northern Mariana Islands',
 'Norway ': 'Norway',
 'Oman ': 'Oman',
 'Pakistan ': 'Pakistan',
 'Palau ': 'Palau',
 'Panama ': 'Panama',
 'Papua New Guinea ': 'Papua New Guinea',
 'Paraguay ': 'Paraguay',
 'Peru ': 'Peru',
 'Philippines ': 'Philippines',
 'Poland ': 'Poland',
 'Portugal ': 'Portugal',
 'Puerto Rico ': 'Puerto Rico',
 'Qatar ': 'Qatar',
 'Reunion ': 'Reunion',
 'Romania ': 'Romania',
 'Russia ': 'Russia',
 'Rwanda ': 'Rwanda',
 'Saint Helena ': 'St. Helena',
 'Saint Kitts & Nevis ': 'St. Kitts and Nevis',
 'Saint Lucia ': 'St. Lucia',
 'St Pierre & Miquelon ': 'St. Pierre and Miquelon',
 'Saint Vincent and the Grenadines ': 'St. Vincent and the Grenadines',
 'Samoa ': 'Samoa',
 'San Marino ': 'San Marino',
 'Sao Tome & Principe ': 'Sao Tome and Principe',
 'Saudi Arabia ': 'Saudi Arabia',
 'Senegal ': 'Senegal',
 'Serbia ': 'Serbia',
 'Seychelles ': 'Seychelles',
 'Sierra Leone ': 'Sierra Leone',
 'Singapore ': 'Singapore',
 'Slovakia ': 'Slovakia',
 'Slovenia ': 'Slovenia',
 'Solomon Islands ': 'Solomon Islands',
 'Somalia ': 'Somalia',
 'South Africa ': 'South Africa',
 'Spain ': 'Spain',
 'Sri Lanka ': 'Sri Lanka',
 'Sudan ': 'Sudan',
 'Suriname ': 'Suriname',
 'Swaziland ': 'Eswatini',
 'Sweden ': 'Sweden',
 'Switzerland ': 'Switzerland',
 'Syria ': 'Syria',
 'Taiwan ': 'Taiwan',
 'Tajikistan ': 'Tajikistan',
 'Tanzania ': 'Tanzania',
 'Thailand ': 'Thailand',
 'Togo ': 'Togo',
 'Tonga ': 'Tonga',
 'Trinidad & Tobago ': 'Trinidad and Tobago',
 'Tunisia ': 'Tunisia',
 'Turkey ': 'Turkey',
 'Turkmenistan ': 'Turkmenistan',
 'Turks & Caicos Is ': 'Turks and Caicos Islands',
 'Tuvalu ': 'Tuvalu',
 'Uganda ': 'Uganda',
 'Ukraine ': 'Ukraine',
 'United Arab Emirates ': 'United Arab Emirates',
 'United Kingdom ': 'United Kingdom',
 'United States ': 'United States',
 'Uruguay ': 'Uruguay',
 'Uzbekistan ': 'Uzbekistan',
 'Vanuatu ': 'Vanuatu',
 'Venezuela ': 'Venezuela',
 'Vietnam ': 'Vietnam',
 'Wallis and Futuna ': 'Wallis and Futuna Islands',
 'West Bank ': 'Palestine',
 'Western Sahara ': 'Western Sahara',
 'Yemen ': 'Yemen',
 'Zambia ': 'Zambia',
 'Zimbabwe ': 'Zimbabwe'}

In [50]:
# substitute values
countries.loc[:,'Country'].replace(to_replace = dic.keys(), value = dic.values() , inplace=True)

In [51]:
countries.loc[:,'Country'].value_counts()

Palestine              2
Zambia                 1
Timor-Leste            1
American Samoa         1
Benin                  1
                      ..
Antigua and Barbuda    1
Hungary                1
Spain                  1
Jersey                 1
Oman                   1
Name: Country, Length: 226, dtype: int64

In [52]:
#delaing with duplicates in country's
countries.drop_duplicates(subset ="Country", 
                     keep = "first", inplace = True)
countries.loc[:,'Country'].value_counts()

Zambia                       1
Timor-Leste                  1
Wallis and Futuna Islands    1
American Samoa               1
Benin                        1
                            ..
Guam                         1
Antigua and Barbuda          1
Hungary                      1
Spain                        1
Oman                         1
Name: Country, Length: 226, dtype: int64

In [53]:
covid_df.head()

,Country,Continent,Confirmed,Deaths,Recovered,latitude,longitude,Active Cases
ObservationDate,,,,,,,,
2020-01-22,China,Asia,547.0,17.0,28.0,35.861660,104.195397,502.0
2020-01-22,Hong Kong,Asia,0.0,0.0,0.0,22.396428,114.109497,0.0
2020-01-22,Japan,Asia,2.0,0.0,0.0,36.204824,138.252924,2.0
2020-01-22,Macao,Asia,1.0,0.0,0.0,22.198745,113.543873,1.0
2020-01-22,South Korea,Asia,1.0,0.0,0.0,35.907757,127.766922,1.0

In [54]:
covid_df["ObservationDate"] = covid_df.index
corona_countries = pd.merge(left=covid_df, right=countries, how='left', left_index=True, left_on='Country', right_on='Country')
corona_countries.set_index("ObservationDate", inplace=True)
corona_countries.head()

,Country,Continent,Confirmed,Deaths,Recovered,latitude,longitude,Active Cases,Population,Area (sq. mi.),Pop. Density (per sq. mi.),Net migration,GDP ($ per capita)
ObservationDate,,,,,,,,,,,,,
2020-01-22,China,Asia,547.0,17.0,28.0,35.861660,104.195397,502.0,1.313974e+09,9596960.0,"136,9","-0,4",5000.0
2020-01-22,Hong Kong,Asia,0.0,0.0,0.0,22.396428,114.109497,0.0,6.940432e+06,1092.0,"6355,7","5,24",28800.0
2020-01-22,Japan,Asia,2.0,0.0,0.0,36.204824,138.252924,2.0,1.274636e+08,377835.0,"337,4",0,28200.0
2020-01-22,Macao,Asia,1.0,0.0,0.0,22.198745,113.543873,1.0,4.531250e+05,28.0,"16183,0","4,86",19400.0
2020-01-22,South Korea,Asia,1.0,0.0,0.0,35.907757,127.766922,1.0,4.884682e+07,98480.0,"496,0",0,17800.0

In [55]:
print(corona_countries.shape)
print(covid_df.shape)

(3872, 13)
(3872, 9)

In [56]:
corona_countries.to_csv("Corona_Visualization")

In [57]:
corona_countries.isnull().sum()

Country                        0
Continent                      0
Confirmed                      0
Deaths                         0
Recovered                      0
latitude                       0
longitude                      0
Active Cases                   0
Population                    42
Area (sq. mi.)                42
Pop. Density (per sq. mi.)    42
Net migration                 42
GDP ($ per capita)            42
dtype: int64

In [58]:
corona_viz = corona_countries.fillna(0)

##### Saving the dataframe which will be later used for visusualization

In [59]:
corona_viz.to_csv("corona_viz.csv")

In [60]:
corona_pred = corona_viz.copy()
corona_pred.columns

Index(['Country', 'Continent', 'Confirmed', 'Deaths', 'Recovered', 'latitude',
       'longitude', 'Active Cases', 'Population', 'Area (sq. mi.)',
       'Pop. Density (per sq. mi.)', 'Net migration', 'GDP ($ per capita)'],
      dtype='object')

In [61]:
del corona_pred['latitude']
del corona_pred['longitude']
#del corona_pred['GDP ($ per capita)']

corona_pred.head()

,Country,Continent,Confirmed,Deaths,Recovered,Active Cases,Population,Area (sq. mi.),Pop. Density (per sq. mi.),Net migration,GDP ($ per capita)
ObservationDate,,,,,,,,,,,
2020-01-22,China,Asia,547.0,17.0,28.0,502.0,1.313974e+09,9596960.0,"136,9","-0,4",5000.0
2020-01-22,Hong Kong,Asia,0.0,0.0,0.0,0.0,6.940432e+06,1092.0,"6355,7","5,24",28800.0
2020-01-22,Japan,Asia,2.0,0.0,0.0,2.0,1.274636e+08,377835.0,"337,4",0,28200.0
2020-01-22,Macao,Asia,1.0,0.0,0.0,1.0,4.531250e+05,28.0,"16183,0","4,86",19400.0
2020-01-22,South Korea,Asia,1.0,0.0,0.0,1.0,4.884682e+07,98480.0,"496,0",0,17800.0

##### Dataframe coroa_pred will be used for regression algorithms to predict

In [62]:
corona_pred.to_csv("corona_pred.csv")

In [63]:
#think of china as an outlier
corona_pred_china = corona_pred.loc[corona_pred['Country'] != "China"]
corona_pred_china.to_csv("corona_pred_china.csv")

In [64]:
corona_pred_china.shape

(3811, 11)

#### Filter Europe continent data from the main dataset to use it in the model training

In [65]:
#only taking into account European countries

#Europe Country unique values list creation
europe = covid_df[covid_df['Continent'] == "Europe"]['Country'].values
europe = set(europe)
europe = list(europe)

#df with only countries in Europe
europe_pred = corona_pred[corona_pred['Country'].isin(europe)]
europe_pred.shape

(1256, 11)

In [66]:
europe_pred.to_csv("europe_pred.csv")